import '@testing-library/jest-dom';

// lightweight-charts / fancy-canvas requires these APIs which jsdom doesn't implement.
// Stub them so unhandled promise rejections don't fail the test suite.
Object.defineProperty(window, 'matchMedia', {
  writable: true,
  value: (query: string) => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: () => {},
    removeListener: () => {},
    addEventListener: () => {},
    removeEventListener: () => {},
    dispatchEvent: () => false,
  }),
});

const mockCanvas2d = {
  canvas: {} as HTMLCanvasElement,
  clearRect: () => {},
  fillRect: () => {},
  strokeRect: () => {},
  beginPath: () => {},
  closePath: () => {},
  moveTo: () => {},
  lineTo: () => {},
  stroke: () => {},
  fill: () => {},
  arc: () => {},
  rect: () => {},
  save: () => {},
  restore: () => {},
  translate: () => {},
  scale: () => {},
  rotate: () => {},
  setTransform: () => {},
  resetTransform: () => {},
  createLinearGradient: () => ({ addColorStop: () => {} }),
  createRadialGradient: () => ({ addColorStop: () => {} }),
  createPattern: () => null,
  drawImage: () => {},
  getImageData: () => ({ data: new Uint8ClampedArray(0), width: 0, height: 0, colorSpace: 'srgb' as PredefinedColorSpace }),
  putImageData: () => {},
  measureText: () => ({ width: 0, actualBoundingBoxLeft: 0, actualBoundingBoxRight: 0, fontBoundingBoxAscent: 0, fontBoundingBoxDescent: 0, actualBoundingBoxAscent: 0, actualBoundingBoxDescent: 0, emHeightAscent: 0, emHeightDescent: 0, hangingBaseline: 0, alphabeticBaseline: 0, ideographicBaseline: 0 }),
  fillText: () => {},
  strokeText: () => {},
  clip: () => {},
  isPointInPath: () => false,
  isPointInStroke: () => false,
  fillStyle: '',
  strokeStyle: '',
  lineWidth: 1,
  lineCap: 'butt' as CanvasLineCap,
  lineJoin: 'miter' as CanvasLineJoin,
  font: '',
  textAlign: 'start' as CanvasTextAlign,
  textBaseline: 'alphabetic' as CanvasTextBaseline,
  globalAlpha: 1,
  globalCompositeOperation: 'source-over' as GlobalCompositeOperation,
  shadowBlur: 0,
  shadowColor: '',
  shadowOffsetX: 0,
  shadowOffsetY: 0,
  miterLimit: 10,
  lineDashOffset: 0,
  getLineDash: () => [] as number[],
  setLineDash: () => {},
  createImageData: () => ({ data: new Uint8ClampedArray(0), width: 0, height: 0, colorSpace: 'srgb' as PredefinedColorSpace }),
  drawFocusIfNeeded: () => {},
  direction: 'ltr' as CanvasDirection,
  imageSmoothingEnabled: true,
  imageSmoothingQuality: 'low' as ImageSmoothingQuality,
  getTransform: () => new DOMMatrix(),
  filter: 'none',
  letterSpacing: '0px',
  wordSpacing: '0px',
  fontKerning: 'auto' as CanvasFontKerning,
  fontStretch: 'normal' as CanvasFontStretch,
  fontVariantCaps: 'normal' as CanvasFontVariantCaps,
  textRendering: 'auto' as CanvasTextRendering,
  roundRect: () => {},
  bezierCurveTo: () => {},
  quadraticCurveTo: () => {},
  ellipse: () => {},
} as unknown as CanvasRenderingContext2D;

Object.defineProperty(HTMLCanvasElement.prototype, 'getContext', {
  writable: true,
  value: () => mockCanvas2d,
});
